version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - .:/home/node
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    networks:
      - app-network
    volumes:
      - data:/data/db

networks:
    app-network:
        driver: bridge

volumes:
  data:
