version: '3'

services:
  web:
    build: .
    ports:
      - "${PORT}:3000"
    networks:
      - app-network
    environment:
      - DB_URI=${DB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_ESCRET=${CLOUDINARY_API_ESCRET}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
  data:
